### PR TITLE
Update fcp-0000.md

### PR DESCRIPTION
**Pull request by stesser**
The sample file name should not have a number in the reserved range < 100.

### CODE REVIEW

**Comment by stesser** [comment]
Perhaps only mention here, that attachments may be added to the FCP, without going into detail with regard to the file names of such attachments. 
The FCP number has not been allocted at this stage (when following the outline procedure) and the naming of attachments could be specified together with the rules for the FCP name/number (i.e., at the end of the "submit FCP" section).

**Comment by jeamland** [comment]
@allanjude What're your thoughts on this?

**Comment by allanjude** [comment]
Based on the discussion Benno and I had, the FCP # will be self allocated at the time the pull request is created, so the files can be renamed/numbered then. If there ends up being a conflict, it is pretty straight forward to renumber things.

**Comment by jeamland** [comment]
I think as example text it's ok so I'm going to leave it alone for now.

**Pull request closed without merging**
